name: study_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0

  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
